
persistence:
  path: "../../../rawdata/with-bucket"

mqtt:
  host: "localhost:1883"
  id: "edash-energystore"
  qos: 1
#  energySubscriptionTopic: "eda/response/energy/+"
  energySubscriptionTopic: "eda/response/+/protocol/cr_msg"
  inverterSubscriptionTopic: "eda/response/+/protocol/inverter_msg"
services:
  mail-server: "localhost:9090"
  master-server: "localhost:9092"
